/**
 * ISO 3166-1 alpha-2, every UN member and observer plus Taiwan, Hong Kong and
 * Kosovo. Names come from Intl.DisplayNames so they match what a browser would
 * render; `alias` carries the names people actually type.
 */
export interface Country {
  code: string
  name: string
  /** E.164 calling code, with the plus. */
  dial: string
  /** Extra search terms — "uk", "holland", "burma". */
  alias?: string[]
}

export const COUNTRIES: Country[] = [
  { code: "AD", name: "Andorra", dial: "+376" },
  { code: "AE", name: "United Arab Emirates", dial: "+971", alias: ["uae"] },
  { code: "AF", name: "Afghanistan", dial: "+93" },
  { code: "AG", name: "Antigua & Barbuda", dial: "+1268" },
  { code: "AL", name: "Albania", dial: "+355" },
  { code: "AM", name: "Armenia", dial: "+374" },
  { code: "AO", name: "Angola", dial: "+244" },
  { code: "AR", name: "Argentina", dial: "+54" },
  { code: "AT", name: "Austria", dial: "+43" },
  { code: "AU", name: "Australia", dial: "+61" },
  { code: "AZ", name: "Azerbaijan", dial: "+994" },
  { code: "BA", name: "Bosnia & Herzegovina", dial: "+387" },
  { code: "BB", name: "Barbados", dial: "+1246" },
  { code: "BD", name: "Bangladesh", dial: "+880" },
  { code: "BE", name: "Belgium", dial: "+32" },
  { code: "BF", name: "Burkina Faso", dial: "+226" },
  { code: "BG", name: "Bulgaria", dial: "+359" },
  { code: "BH", name: "Bahrain", dial: "+973" },
  { code: "BI", name: "Burundi", dial: "+257" },
  { code: "BJ", name: "Benin", dial: "+229" },
  { code: "BN", name: "Brunei", dial: "+673", alias: ["brunei"] },
  { code: "BO", name: "Bolivia", dial: "+591", alias: ["bolivia"] },
  { code: "BR", name: "Brazil", dial: "+55" },
  { code: "BS", name: "Bahamas", dial: "+1242" },
  { code: "BT", name: "Bhutan", dial: "+975" },
  { code: "BW", name: "Botswana", dial: "+267" },
  { code: "BY", name: "Belarus", dial: "+375" },
  { code: "BZ", name: "Belize", dial: "+501" },
  { code: "CA", name: "Canada", dial: "+1" },
  { code: "CD", name: "Congo - Kinshasa", dial: "+243", alias: ["drc", "congo kinshasa"] },
  { code: "CF", name: "Central African Republic", dial: "+236" },
  { code: "CG", name: "Congo - Brazzaville", dial: "+242", alias: ["congo brazzaville"] },
  { code: "CH", name: "Switzerland", dial: "+41" },
  { code: "CI", name: "Côte d’Ivoire", dial: "+225", alias: ["ivory coast"] },
  { code: "CL", name: "Chile", dial: "+56" },
  { code: "CM", name: "Cameroon", dial: "+237" },
  { code: "CN", name: "China", dial: "+86" },
  { code: "CO", name: "Colombia", dial: "+57" },
  { code: "CR", name: "Costa Rica", dial: "+506" },
  { code: "CU", name: "Cuba", dial: "+53" },
  { code: "CV", name: "Cape Verde", dial: "+238", alias: ["cape verde"] },
  { code: "CY", name: "Cyprus", dial: "+357" },
  { code: "CZ", name: "Czechia", dial: "+420", alias: ["czechia"] },
  { code: "DE", name: "Germany", dial: "+49" },
  { code: "DJ", name: "Djibouti", dial: "+253" },
  { code: "DK", name: "Denmark", dial: "+45" },
  { code: "DM", name: "Dominica", dial: "+1767" },
  { code: "DO", name: "Dominican Republic", dial: "+1809" },
  { code: "DZ", name: "Algeria", dial: "+213" },
  { code: "EC", name: "Ecuador", dial: "+593" },
  { code: "EE", name: "Estonia", dial: "+372" },
  { code: "EG", name: "Egypt", dial: "+20" },
  { code: "ER", name: "Eritrea", dial: "+291" },
  { code: "ES", name: "Spain", dial: "+34" },
  { code: "ET", name: "Ethiopia", dial: "+251" },
  { code: "FI", name: "Finland", dial: "+358" },
  { code: "FJ", name: "Fiji", dial: "+679" },
  { code: "FM", name: "Micronesia", dial: "+691" },
  { code: "FR", name: "France", dial: "+33" },
  { code: "GA", name: "Gabon", dial: "+241" },
  { code: "GB", name: "United Kingdom", dial: "+44", alias: ["uk", "great britain", "england", "scotland", "wales", "britain"] },
  { code: "GD", name: "Grenada", dial: "+1473" },
  { code: "GE", name: "Georgia", dial: "+995" },
  { code: "GH", name: "Ghana", dial: "+233" },
  { code: "GM", name: "Gambia", dial: "+220" },
  { code: "GN", name: "Guinea", dial: "+224" },
  { code: "GQ", name: "Equatorial Guinea", dial: "+240" },
  { code: "GR", name: "Greece", dial: "+30" },
  { code: "GT", name: "Guatemala", dial: "+502" },
  { code: "GW", name: "Guinea-Bissau", dial: "+245" },
  { code: "GY", name: "Guyana", dial: "+592" },
  { code: "HK", name: "Hong Kong SAR China", dial: "+852" },
  { code: "HN", name: "Honduras", dial: "+504" },
  { code: "HR", name: "Croatia", dial: "+385" },
  { code: "HT", name: "Haiti", dial: "+509" },
  { code: "HU", name: "Hungary", dial: "+36" },
  { code: "ID", name: "Indonesia", dial: "+62" },
  { code: "IE", name: "Ireland", dial: "+353" },
  { code: "IL", name: "Israel", dial: "+972" },
  { code: "IN", name: "India", dial: "+91" },
  { code: "IQ", name: "Iraq", dial: "+964" },
  { code: "IR", name: "Iran", dial: "+98", alias: ["iran"] },
  { code: "IS", name: "Iceland", dial: "+354" },
  { code: "IT", name: "Italy", dial: "+39" },
  { code: "JM", name: "Jamaica", dial: "+1876" },
  { code: "JO", name: "Jordan", dial: "+962" },
  { code: "JP", name: "Japan", dial: "+81" },
  { code: "KE", name: "Kenya", dial: "+254" },
  { code: "KG", name: "Kyrgyzstan", dial: "+996" },
  { code: "KH", name: "Cambodia", dial: "+855" },
  { code: "KI", name: "Kiribati", dial: "+686" },
  { code: "KM", name: "Comoros", dial: "+269" },
  { code: "KN", name: "St. Kitts & Nevis", dial: "+1869" },
  { code: "KP", name: "North Korea", dial: "+850", alias: ["north korea"] },
  { code: "KR", name: "South Korea", dial: "+82", alias: ["south korea"] },
  { code: "KW", name: "Kuwait", dial: "+965" },
  { code: "KZ", name: "Kazakhstan", dial: "+7" },
  { code: "LA", name: "Laos", dial: "+856", alias: ["laos"] },
  { code: "LB", name: "Lebanon", dial: "+961" },
  { code: "LC", name: "St. Lucia", dial: "+1758" },
  { code: "LI", name: "Liechtenstein", dial: "+423" },
  { code: "LK", name: "Sri Lanka", dial: "+94" },
  { code: "LR", name: "Liberia", dial: "+231" },
  { code: "LS", name: "Lesotho", dial: "+266" },
  { code: "LT", name: "Lithuania", dial: "+370" },
  { code: "LU", name: "Luxembourg", dial: "+352" },
  { code: "LV", name: "Latvia", dial: "+371" },
  { code: "LY", name: "Libya", dial: "+218" },
  { code: "MA", name: "Morocco", dial: "+212" },
  { code: "MC", name: "Monaco", dial: "+377" },
  { code: "MD", name: "Moldova", dial: "+373", alias: ["moldova"] },
  { code: "ME", name: "Montenegro", dial: "+382" },
  { code: "MG", name: "Madagascar", dial: "+261" },
  { code: "MH", name: "Marshall Islands", dial: "+692" },
  { code: "MK", name: "North Macedonia", dial: "+389", alias: ["macedonia"] },
  { code: "ML", name: "Mali", dial: "+223" },
  { code: "MM", name: "Myanmar (Burma)", dial: "+95", alias: ["burma"] },
  { code: "MN", name: "Mongolia", dial: "+976" },
  { code: "MR", name: "Mauritania", dial: "+222" },
  { code: "MT", name: "Malta", dial: "+356" },
  { code: "MU", name: "Mauritius", dial: "+230" },
  { code: "MV", name: "Maldives", dial: "+960" },
  { code: "MW", name: "Malawi", dial: "+265" },
  { code: "MX", name: "Mexico", dial: "+52" },
  { code: "MY", name: "Malaysia", dial: "+60" },
  { code: "MZ", name: "Mozambique", dial: "+258" },
  { code: "NA", name: "Namibia", dial: "+264" },
  { code: "NE", name: "Niger", dial: "+227" },
  { code: "NG", name: "Nigeria", dial: "+234" },
  { code: "NI", name: "Nicaragua", dial: "+505" },
  { code: "NL", name: "Netherlands", dial: "+31", alias: ["holland"] },
  { code: "NO", name: "Norway", dial: "+47" },
  { code: "NP", name: "Nepal", dial: "+977" },
  { code: "NR", name: "Nauru", dial: "+674" },
  { code: "NZ", name: "New Zealand", dial: "+64" },
  { code: "OM", name: "Oman", dial: "+968" },
  { code: "PA", name: "Panama", dial: "+507" },
  { code: "PE", name: "Peru", dial: "+51" },
  { code: "PG", name: "Papua New Guinea", dial: "+675" },
  { code: "PH", name: "Philippines", dial: "+63" },
  { code: "PK", name: "Pakistan", dial: "+92" },
  { code: "PL", name: "Poland", dial: "+48" },
  { code: "PS", name: "Palestinian Territories", dial: "+970" },
  { code: "PT", name: "Portugal", dial: "+351" },
  { code: "PW", name: "Palau", dial: "+680" },
  { code: "PY", name: "Paraguay", dial: "+595" },
  { code: "QA", name: "Qatar", dial: "+974" },
  { code: "RO", name: "Romania", dial: "+40" },
  { code: "RS", name: "Serbia", dial: "+381" },
  { code: "RU", name: "Russia", dial: "+7", alias: ["russian federation"] },
  { code: "RW", name: "Rwanda", dial: "+250" },
  { code: "SA", name: "Saudi Arabia", dial: "+966" },
  { code: "SB", name: "Solomon Islands", dial: "+677" },
  { code: "SC", name: "Seychelles", dial: "+248" },
  { code: "SD", name: "Sudan", dial: "+249" },
  { code: "SE", name: "Sweden", dial: "+46" },
  { code: "SG", name: "Singapore", dial: "+65" },
  { code: "SI", name: "Slovenia", dial: "+386" },
  { code: "SK", name: "Slovakia", dial: "+421" },
  { code: "SL", name: "Sierra Leone", dial: "+232" },
  { code: "SM", name: "San Marino", dial: "+378" },
  { code: "SN", name: "Senegal", dial: "+221" },
  { code: "SO", name: "Somalia", dial: "+252" },
  { code: "SR", name: "Suriname", dial: "+597" },
  { code: "SS", name: "South Sudan", dial: "+211" },
  { code: "ST", name: "São Tomé & Príncipe", dial: "+239" },
  { code: "SV", name: "El Salvador", dial: "+503" },
  { code: "SY", name: "Syria", dial: "+963", alias: ["syrian arab republic"] },
  { code: "SZ", name: "Eswatini", dial: "+268", alias: ["swaziland"] },
  { code: "TD", name: "Chad", dial: "+235" },
  { code: "TG", name: "Togo", dial: "+228" },
  { code: "TH", name: "Thailand", dial: "+66" },
  { code: "TJ", name: "Tajikistan", dial: "+992" },
  { code: "TL", name: "Timor-Leste", dial: "+670", alias: ["east timor"] },
  { code: "TM", name: "Turkmenistan", dial: "+993" },
  { code: "TN", name: "Tunisia", dial: "+216" },
  { code: "TO", name: "Tonga", dial: "+676" },
  { code: "TR", name: "Türkiye", dial: "+90" },
  { code: "TT", name: "Trinidad & Tobago", dial: "+1868" },
  { code: "TV", name: "Tuvalu", dial: "+688" },
  { code: "TW", name: "Taiwan", dial: "+886", alias: ["taiwan"] },
  { code: "TZ", name: "Tanzania", dial: "+255", alias: ["tanzania"] },
  { code: "UA", name: "Ukraine", dial: "+380" },
  { code: "UG", name: "Uganda", dial: "+256" },
  { code: "US", name: "United States", dial: "+1", alias: ["usa", "united states of america", "america"] },
  { code: "UY", name: "Uruguay", dial: "+598" },
  { code: "UZ", name: "Uzbekistan", dial: "+998" },
  { code: "VA", name: "Vatican City", dial: "+39", alias: ["vatican"] },
  { code: "VC", name: "St. Vincent & Grenadines", dial: "+1784" },
  { code: "VE", name: "Venezuela", dial: "+58", alias: ["venezuela"] },
  { code: "VN", name: "Vietnam", dial: "+84", alias: ["viet nam"] },
  { code: "VU", name: "Vanuatu", dial: "+678" },
  { code: "WS", name: "Samoa", dial: "+685" },
  { code: "XK", name: "Kosovo", dial: "+383", alias: ["kosovo"] },
  { code: "YE", name: "Yemen", dial: "+967" },
  { code: "ZA", name: "South Africa", dial: "+27" },
  { code: "ZM", name: "Zambia", dial: "+260" },
  { code: "ZW", name: "Zimbabwe", dial: "+263" },
]
